### PR TITLE
Handle bad service syntax gracefully (fixes #27)

### LINKED ISSUE #27: "wait-for-it -s ::1:1234" crashes with ValueError: invalid literal for int() with base 10: ':1:1234'
```
$ wait-for-it -s ::1:1234
Traceback (most recent call last):
  File "/tmp/tmp.EpOU9tyqoz/py3/bin/wait-for-it", line 33, in <module>
    sys.exit(load_entry_point('wait-for-it', 'console_scripts', 'wait-for-it')())
  File "/tmp/tmp.EpOU9tyqoz/py3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/tmp.EpOU9tyqoz/py3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/tmp.EpOU9tyqoz/py3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/tmp.EpOU9tyqoz/py3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/tmp.EpOU9tyqoz/wait-for-it/wait_for_it/wait_for_it.py", line 98, in cli
    _connect_all_serial(service, timeout)
  File "/tmp/tmp.EpOU9tyqoz/wait-for-it/wait_for_it/wait_for_it.py", line 183, in _connect_all_serial
    connect(service, timeout)
  File "/tmp/tmp.EpOU9tyqoz/wait-for-it/wait_for_it/wait_for_it.py", line 187, in connect
    host, port = _determine_host_and_port_for(service)
  File "/tmp/tmp.EpOU9tyqoz/wait-for-it/wait_for_it/wait_for_it.py", line 32, in _determine_host_and_port_for
    port = url.port or (443 if url.scheme == "https" else 80)
  File "/usr/lib/python3.7/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: ':1:1234'
```

This is caused by the URL service format support introduced at https://github.com/clarketm/wait-for-it/commit/9d8f631939bb686d7d1587766e0381211e83bfe0#diff-ae5818251477f1a9e950145b0ae260dcR36-R41 .

The core is the difference between these two cases:
```
In [18]: urlparse('https://[::1]:1234', scheme="http").port
Out[18]: 1234

In [19]: urlparse('https://::1:1234', scheme="http").port
[..]
ValueError: invalid literal for int() with base 10: ':1:1234'
```

I wonder if a user can expect `::1:1234` or rather `[::1]:1234` to work with `wait-for-it`. The square bracket syntax is from [RFC 3986 section 3.2.2](https://tools.ietf.org/html/rfc3986#section-3.2.2) but we don't always have a full URI here. What do you think? What's the best other tool to check how they handle this issue, especially disambiguation of the colon?

PS: This is not a recently introduced issue so maybe it doesn't need to block the upcoming release but just my 2 cents.

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #27

What do you think?

### CODE REVIEW

**Comment by hartwork** [comment]
PS: @clarketm If this get's merged, my vote for not squashing the commits e.g. because every squash-merged branch with multiple commits leaves two orphan branches on my side — one local and one remote — that my [git-delete-merged-branches](https://github.com/hartwork/git-delete-merged-branches) cannot safely detect as merged, even if I make it query `git cherry` as well in the future. Are you aware of a way to safely auto-detect merges like without doing writes and temporary branches to the repository… or have any ideas about improving my process?

Here's a picture of the orphan merged branches, marked with round-corner rectangles, both source commits and squashed target:

junk_merged_branches

What do you think?

**Comment by clarketm** [comment]
@hartwork thanks for looking into this! I have not had a chance to catch up on your comments but I will do so today and review.

**Comment by hartwork** [comment]
@clarketm looking forward to that, thanks for the update! :+1:

**Comment by clarketm** [comment]
> PS: @clarketm If this get's merged, my vote for not squashing the commits e.g. because every squash-merged branch with multiple commits leaves two orphan branches on my side — one local and one remote — that my [git-delete-merged-branches](https://github.com/hartwork/git-delete-merged-branches) cannot safely detect as merged, even if I make it query `git cherry` as well in the future. Are you aware of a way to safely auto-detect merges like that without adding temporary branches to the repository… or have any ideas about improving my process?

I am fine with regular _merges_ instead of _squash and merges_. My flow probably is not ideal, but I typically set [Automatically delete head branches](https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches) in GH to delete the remote branch on merge then I will run a periodic [command](https://stackoverflow.com/a/33548037/4279440) locally to cleanup local branches.

**Comment by hartwork** [comment]
> I am fine with regular _merges_ instead of _squash and merges_. My flow probably is not ideal, but I typically set [Automatically delete head branches](https://docs.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches) in GH to delete the remote branch on merge then I will run a periodic [command](https://stackoverflow.com/a/33548037/4279440) locally to cleanup local branches.

Okay, thank you!

**Comment by hartwork** [comment]
@clarketm my view on squash merges is unchanged but I've been able to teach a few tricks to [git-delete-merged-branches](https://github.com/hartwork/git-delete-merged-branches) by now so that version 4.1.0 detects multiple forms of de-facto merges and is able to clean all branches shown above, including the squash merges. In case you check it out and find cases where it fails to detect de-facto merges done via GitHub, I'd be curious to hear. Thank you!

**Pull request merged**
