### PR TITLE
Return Exit Code From Executed Command

### PR DESCRIPTION
**Pull request by karthicraghupathi**
Thanks for creating this. I've been using the wait-for-it.sh bash script but I realized I needed something to handle multiple services.

This is my attempt at giving back to the community. I've taken a stab at fixing issue #3 where the request was to return the exit code after executing the command.

### CODE REVIEW

**Comment by clarketm** [comment]
Hi @karthicraghupathi, thanks for the contribution. This is a great idea in order to maintain parity with the `wait-for-it.sh` bash script.

**Comment by clarketm** [comment]
fix https://github.com/clarketm/wait-for-it/issues/3

**Comment by clarketm** [comment]
The release is now available! Thanks again for the contribution.

https://github.com/clarketm/wait-for-it/releases/tag/v2.0.0
https://pypi.org/project/wait-for-it/2.0.0/

**Comment by karthicraghupathi** [comment]
Awesome. You're welcome.

**Pull request merged**
