### PR TITLE
Handle "command not found" error gracefully (fixes #39)

### LINKED ISSUE #39: [2.2.0 and before] Crashes with FileNotFoundError: [Errno 2] No such file or directory: 'xxxxxxxxxxx'
I think we should catch `FileNotFoundError` and do more human-friendly reporting here:

```
# wait-for-it xxxxxxxxxxx
Traceback (most recent call last):
  File "/tmp/tmp.7T0RShGfKQ/venv/bin/wait-for-it", line 8, in <module>
    sys.exit(cli())
  File "/tmp/tmp.7T0RShGfKQ/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/tmp.7T0RShGfKQ/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/tmp.7T0RShGfKQ/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/tmp.7T0RShGfKQ/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/tmp.7T0RShGfKQ/venv/lib/python3.8/site-packages/wait_for_it/wait_for_it.py", line 99, in cli
    _cli_internal(**kwargs)
  File "/tmp/tmp.7T0RShGfKQ/venv/lib/python3.8/site-packages/wait_for_it/wait_for_it.py", line 115, in _cli_internal
    result = subprocess.run(commands)
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xxxxxxxxxxx'
(venv) 

# wait-for-it --version
Version 2.2.0
```

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #39

### CODE REVIEW

**Review by clarketm — APPROVED** [review]

**Comment by clarketm** [comment]
Thanks for the fix @hartwork. I'll have a release out shortly.

**Comment by hartwork** [comment]
@clarketm great, thanks in advance!

**Comment by clarketm** [comment]
@hartwork – released and ready to consume: https://pypi.org/project/wait-for-it/2.2.1/

**Comment by hartwork** [comment]
@clarketm thank you!

**Pull request merged**
