### PR TITLE
Refactoring one for discussion

### PR DESCRIPTION
**Pull request by hartwork**
Hi!

Here's a first small refactoring to build upon. What do you think so far?

### CODE REVIEW

**Comment by hartwork** [comment]
PS: Probably best to review on single-commit level.

**Comment by clarketm** [comment]
> Here's a first small refactoring to build upon. What do you think so far?

lgtm. Clean and easy to follow!

**Comment by hartwork** [comment]
Okay cool! Are you okay to merge and start the next round from there?

**Comment by clarketm** [comment]
> Okay cool! Are you okay to merge and we start the next round off latest `master`?

sgtm!

**Pull request merged**
